global:
  scrape_interval: 5s # Scrape data every 5 seconds (Great for a live demo)

scrape_configs:
  - job_name: 'kong-gateway'
    static_configs:
      # This points to your Kong container's Admin API port
      - targets: ['kong-dbless:8001']

  - job_name: 'error-service'
    static_configs:
      - targets: ['error-service:5007']